APPMVC/Areas/Admin/Controllers/AdminSizesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using APPDATA.DB;
using APPDATA.Models;

namespace APPMVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminSizesController : Controller
    {
        private readonly ShopDbContext _context;

        public AdminSizesController(ShopDbContext context)
        {
            _context = context;
        }

        // GET: Admin/AdminSizes
        public async Task<IActionResult> Index()
        {
              return _context.Sizes != null ? 
                          View(await _context.Sizes.ToListAsync()) :
                          Problem("Entity set 'ShopDbContext.Sizes'  is null.");
        }

        // GET: Admin/AdminSizes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Sizes == null)
            {
                return NotFound();
            }

            var size = await _context.Sizes
                .FirstOrDefaultAsync(m => m.SizeID == id);
            if (size == null)
            {
                return NotFound();
            }

            return View(size);
        }

        // GET: Admin/AdminSizes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminSizes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SizeID,NameSize")] Size size)
        {
            if (ModelState.IsValid)
            {
                _context.Add(size);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(size);
        }

        // GET: Admin/AdminSizes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Sizes == null)
            {
                return NotFound();
            }

            var size = await _context.Sizes.FindAsync(id);
            if (size == null)
            {
                return NotFound();
            }
            return View(size);
        }

        // POST: Admin/AdminSizes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SizeID,NameSize")] Size size)
        {
            if (id != size.SizeID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(size);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SizeExists(size.SizeID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(size);
        }

        // GET: Admin/AdminSizes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Sizes == null)
            {
                return NotFound();
            }

            var size = await _context.Sizes
                .FirstOrDefaultAsync(m => m.SizeID == id);
            if (size == null)
            {
                return NotFound();
            }

            return View(size);
        }

        // POST: Admin/AdminSizes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Sizes == null)
            {
                return Problem("Entity set 'ShopDbContext.Sizes'  is null.");
            }
            var size = await _context.Sizes.FindAsync(id);
            if (size != null)
            {
                _context.Sizes.Remove(size);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SizeExists(int id)
        {
          return (_context.Sizes?.Any(e => e.SizeID == id)).GetValueOrDefault();
        }
    }
}

APPMVC/Areas/Admin/Views/AdminSizes/Create.cshtml
@model APPDATA.Models.Size

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>Size</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NameSize" class="control-label"></label>
                <input asp-for="NameSize" class="form-control" />
                <span asp-validation-for="NameSize" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

APPMVC/Areas/Admin/Views/AdminSizes/Delete.cshtml
@model APPDATA.Models.Size

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header no-gutters has-tab">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Tổng quan</a>
        </li>

    </ul>
</div>
<div class="container-fluid">
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">


            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Thông tin size: @Model.NameSize</h4>
                    <div class="table-responsive">
                        <form asp-action="Delete" asp-route-id="@Model.SizeID">
                            <input type="hidden" asp-for="SizeID" />
                            <table class="product-info-table m-t-20">
                                <tbody>
                                    <tr>
                                        <td>Size:</td>
                                        <td class="text-dark font-weight-semibold">@Model.NameSize</td>
                                    </tr>
                                    
                                    <tr>
                                        <td>Xác nhận xóa chức vụ</td>
                                        <td>
                                            <input type="submit" value="Xác nhận xóa" class="btn btn-danger" />
                                        </td>
                                    </tr>

                                </tbody>
                            </table>
                        </form>
                    </div>
                </div>
            </div>



        </div>

    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

APPMVC/Areas/Admin/Views/AdminSizes/Details.cshtml
@model APPDATA.Models.Size

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header no-gutters has-tab">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Tổng quan</a>
        </li>

    </ul>
</div>
<div class="container-fluid">
    <div class="tab-content m-t-15">
        <div class="tab-pane fade show active" id="product-edit-basic">


            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Thông tin size: @Model.NameSize</h4>
                    <div class="table-responsive">
                            <input type="hidden" asp-for="SizeID" />
                            <table class="product-info-table m-t-20">
                                <tbody>
                                    <tr>
                                        <td>Size:</td>
                                        <td class="text-dark font-weight-semibold">@Model.NameSize</td>
                                    </tr>

                                    

                                </tbody>
                            </table>
                    </div>
                </div>
            </div>



        </div>

    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

APPMVC/Areas/Admin/Views/AdminSizes/Edit.cshtml
@model APPDATA.Models.Size

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Edit</h1>

<h4>Size</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SizeID" />
            <div class="form-group">
                <label asp-for="NameSize" class="control-label"></label>
                <input asp-for="NameSize" class="form-control" />
                <span asp-validation-for="NameSize" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

APPMVC/Areas/Admin/Views/AdminSizes/Index.cshtml
@model IEnumerable<APPDATA.Models.Size>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<div class="card">
    <div class="card-body">
        <a class="btn btn-secondary m-r-5" asp-area="Admin" asp-controller="AdminSizes" asp-action="Create">Create</a>

        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Size</th>
                    </tr>

                </thead>
                <tbody>
                    @if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td scope="row">@item.SizeID</td>
                                <td scope="row">@item.NameSize</td>

                                <td>

                                    <a asp-area="Admin" asp-controller="AdminSizes" asp-action="Edit" asp-route-id="@item.SizeID" class="btn btn-success m-r-5">Edit</a>
                                    <a asp-area="Admin" asp-controller="AdminSizes" asp-action="Details" asp-route-id="@item.SizeID" class="btn btn-info m-r-5">Details</a>
                                    <a asp-area="Admin" asp-controller="AdminSizes" asp-action="Delete" asp-route-id="@item.SizeID" class="btn btn-warning m-r-5">Delete</a>

                                </td>
                            </tr>

                        }
                    }
                </tbody>
            </table>

        </div>
    </div>
</div>